### ISSUE TITLE
Create timeline detail view

### ISSUE THREAD

**Issue by dt2patel** [hotwax/commerce-hub#121]
One mobile, the timeline view on the order detail page should open up in another page instead of inline since there isn't enough space.

<img width="324" alt="Screen Shot 2022-04-19 at 4 12 12 PM" src="https://user-images.githubusercontent.com/60128132/163986896-64e0b985-d30e-4732-a767-5b5984a7d4a8.png">

**Comment by Dhiraj1405** [comment]
Not a priority. So closing this task for now.
