### ISSUE TITLE
Sort toggle button not working 

### ISSUE THREAD

**Issue by palash018** [hotwax/commerce-hub#185]
## What is the motivation for adding/enhancing this feature?
There is already a button which seems like it is for sorting by Asc and desc but it isn't working
## What are the acceptance criteria?
Items are displayed to user on reverse order after clicking button if it was asc before it should be desc and vice-versa

## Can you complete this feature request by yourself?

- [ X] YES
- [ ] NO

## Additional information
Please assign this to me

https://github.com/hotwax/commerce-hub/assets/109908523/b1f5f177-6daf-4ece-af93-f6f3cbb1b1ab

**Comment by ymaheshwari1** [comment]
Hi @palash018 
Are you having any error/warnings in console?

Also I would suggest to check other apps, like fulfillment, picking, inventorycount etc for issues.

**Comment by palash018** [comment]
@ymaheshwari1 There are no additional errors and warnings when i click on that button but i have warnings and errors which are already present before the button press also you are asking me to look for similar sorting issue in other repos right? 
also when i click on the button there is some change happening in inspect element that means it is calling something but the expected result is not happening
![Screenshot 2023-08-18 220649](https://github.com/hotwax/commerce-hub/assets/109908523/d6fb590d-f477-4d99-a971-47d9acef9577)

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 There are no additional errors and warnings when i click on that button but i have warnings and errors which are already present before the button press also you are asking me to look for similar sorting issue in other repos right? also when i click on the button there is some change happening in inspect element that means it is calling something but the expected result is not happening ![Screenshot 2023-08-18 220649](https://user-images.githubusercontent.com/109908523/261663721-d6fb590d-f477-4d99-a971-47d9acef9577.png)

No I am not asking for finding similar issue in other repos, I am generally asking to check other repos for contribution.

Also I think it should work, as the options for select are hardcoded in the code.

**Comment by palash018** [comment]
Alright @ymaheshwari1 are you able to reproduce this issue?

**Comment by ymaheshwari1** [comment]
> Alright @ymaheshwari1 are you able to reproduce this issue?

No, everything is working as expected.

**Comment by Dhiraj1405** [comment]
Not priority for now. Hence, closing this issue.
